AWSTemplateFormatVersion: '2010-09-09'
Description: 'Déploiement de l\'outil d\'extraction de factures PDF avec AWS Bedrock'

Parameters:
  EnvironmentName:
    Type: String
    Description: Nom de l'environnement (dev, staging, prod)
    Default: dev
  
  BucketName:
    Type: String
    Description: Nom du bucket S3 pour les factures
    Default: invoice-input-bucket
  
  TableName:
    Type: String
    Description: Nom de la table DynamoDB
    Default: invoices
  
  BedrockModelId:
    Type: String
    Description: ID du modèle Bedrock à utiliser
    Default: anthropic.claude-3-sonnet-20240229-v1:0

Resources:
  # S3 Bucket pour les factures
  InvoiceInputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: MoveToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 365
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: invoice-extractor

  # Table DynamoDB pour les factures extraites
  InvoicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: invoice_id
          AttributeType: S
        - AttributeName: numero_facture
          AttributeType: S
        - AttributeName: date_facture
          AttributeType: S
        - AttributeName: fournisseur
          AttributeType: S
      KeySchema:
        - AttributeName: invoice_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: numero_facture-index
          KeySchema:
            - AttributeName: numero_facture
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: date_facture-index
          KeySchema:
            - AttributeName: date_facture
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: fournisseur-index
          KeySchema:
            - AttributeName: fournisseur
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: invoice-extractor

  # Rôle IAM pour Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: 
                  - !Sub arn:aws:s3:::${BucketName}/*
                  - !Sub arn:aws:s3:::${BucketName}
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                Resource: !GetAtt InvoicesTable.Arn
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/${BedrockModelId}
              - Effect: Allow
                Action:
                  - bedrock:ListFoundationModels
                Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  # Fonction Lambda
  InvoiceExtractorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub invoice-extractor-${EnvironmentName}
      Description: 'Extrait les informations de factures PDF avec Bedrock'
      Runtime: python3.9
      Handler: src/main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          # Le code sera uploadé séparément
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps({'message': 'Code à déployer'})
              }
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          DYNAMODB_TABLE_NAME: !Ref TableName
          S3_INPUT_BUCKET: !Ref BucketName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          LOG_LEVEL: INFO
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: invoice-extractor

  # Permission pour S3 d'appeler Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref InvoiceExtractorLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${BucketName}

  # Configuration de notification S3
  BucketNotification:
    Type: Custom::S3BucketNotification
    DependsOn:
      - InvoiceExtractorLambda
      - LambdaInvokePermission
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:s3-bucket-notification-custom-resource
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaFunctionConfigurations:
          - Events:
              - s3:ObjectCreated:*
            LambdaFunctionArn: !GetAtt InvoiceExtractorLambda.Arn
            Filter:
              Key:
                FilterRules:
                  - Name: suffix
                    Value: .pdf

  # CloudWatch Log Group pour Lambda
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${InvoiceExtractorLambda}
      RetentionInDays: 30

  # Alarme CloudWatch pour erreurs Lambda
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub invoice-extractor-errors-${EnvironmentName}
      AlarmDescription: 'Alarme pour les erreurs de la fonction Lambda'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref InvoiceExtractorLambda
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alarm-notifications

  # Alarme CloudWatch pour durée d'exécution
  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub invoice-extractor-duration-${EnvironmentName}
      AlarmDescription: 'Alarme pour durée d\'exécution excessive'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 240000  # 4 minutes (80% du timeout)
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref InvoiceExtractorLambda
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alarm-notifications

Outputs:
  BucketName:
    Description: Nom du bucket S3 pour les factures
    Value: !Ref BucketName
  
  TableName:
    Description: Nom de la table DynamoDB
    Value: !Ref TableName
  
  LambdaFunctionName:
    Description: Nom de la fonction Lambda
    Value: !Ref InvoiceExtractorLambda
  
  LambdaFunctionArn:
    Description: ARN de la fonction Lambda
    Value: !GetAtt InvoiceExtractorLambda.Arn
  
  S3BucketArn:
    Description: ARN du bucket S3
    Value: !GetAtt InvoiceInputBucket.Arn
  
  DynamoDBTableArn:
    Description: ARN de la table DynamoDB
    Value: !GetAtt InvoicesTable.Arn
